name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Deploy app to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          set -e

          # Prepare app folder
          mkdir -p /home/ec2-user/app
          cd /home/ec2-user/app
          
          # Write app.py
          cat > app.py <<'EOF'
          from flask import Flask

          app = Flask(__name__)

          @app.route("/")
          def home():
              return "<h1>Welcome to Qucoon Academy</h1><p>Learning cloud at Qucoon engineering and architecture!</p>"

          if __name__ == "__main__":
              app.run(host="0.0.0.0", port=5000)
          EOF

          # Write requirements.txt
          cat > requirements.txt <<'EOF'
          flask==2.2.5
          EOF

          # Install Python and Flask
          sudo yum install -y python3 || sudo apt-get install -y python3
          /usr/bin/python3 -m pip install --upgrade pip
          /usr/bin/python3 -m pip install -r requirements.txt

          # Create systemd service
          sudo tee /etc/systemd/system/qucoon.service > /dev/null <<'EOF'
          [Unit]
          Description=Qucoon Flask App
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory=/home/ec2-user/app
          ExecStart=/usr/bin/python3 /home/ec2-user/app/app.py
          Restart=always

          [Install]
          WantedBy=multi-user.target
          EOF

          # Start the service
          sudo systemctl daemon-reload
          sudo systemctl enable qucoon.service
          sudo systemctl restart qucoon.service
          sudo systemctl status qucoon.service